---
name: Build and Publish


on:
  push:
    branches:
      - master
  pull_request:


jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./purpleair-to-mqtt
          tags: |
            n0c.io/jlrgraham/purpleair-to-mqtt:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
